### PR TITLE
harryWonder Added Xml Response

### PR DESCRIPTION
**Pull request by harryWonder**
I tested this on the browser and it works fine. However, when I try testing the endpoint that returns the XML content on Postman, Postman kinda breaks the response with some parsing errors. I will find a way to work around this at my end but please do check too. Cheers!

### CODE REVIEW

**Comment by CITGuru** [comment]
I just merged this, I will be checking the scenario you talked about.

**Comment by CITGuru** [comment]
I don't think there are any issues with this, I just tried it out and it works on postman

**Comment by harryWonder** [comment]
Perhaps it's my postman version then. Thanks bro..

**Comment by CITGuru** [comment]
Yeah. I am looking at how to implement named router and make the resolver smart. Should I separate the resolver

**Pull request merged**
